name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download FFmpeg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest -Uri "https://github.com/GyanD/codexffmpeg/releases/download/2023-11-20-git-740702d765/ffmpeg-2023-11-20-git-740702d765-full_build.zip" -OutFile "ffmpeg.zip"
        Expand-Archive -Path ffmpeg.zip -DestinationPath ffmpeg_extracted
        Copy-Item -Path "ffmpeg_extracted\*\bin\ffmpeg.exe" -Destination ".\ffmpeg.exe"
        Remove-Item ffmpeg.zip
        Remove-Item -Recurse -Force ffmpeg_extracted

    - name: Build with PyInstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --noconsole --onefile --name "VideoEditor" main.py

    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --noconsole --onefile --add-binary "ffmpeg.exe;." --name "VideoEditor" main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VideoEditor-${{ matrix.os }}
        path: dist/*
